name: "CI"

env:
    FOUNDRY_PROFILE: "ci"

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    lint:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Check out the repo"
              uses: "actions/checkout@v3"
              with:
                  submodules: "recursive"

            - name: "Install Node.js"
              uses: "actions/setup-node@v3"
              with:
                  node-version: "lts/*"

            - name: "Install the Node.js dependencies"
              run: "npm install"

            - name: "Lint the contracts"
              run: "npm run lint"

            - name: "Add lint summary"
              run: |
                  echo "## Lint result" >> $GITHUB_STEP_SUMMARY
                  echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

    proposal-simulator-test:
        needs: ["lint"]
        runs-on: "ubuntu-latest"
        steps:
            - name: "Check out the repo"
              uses: "actions/checkout@v3"
              with:
                  submodules: "recursive"

            - name: "Install Foundry"
              uses: "foundry-rs/foundry-toolchain@v1"

            - name: "Show the Foundry config"
              run: "forge config"

            - name:
                  "Generate a fuzz seed that changes weekly to avoid burning through RPC
                  allowance"
              run: >
                  echo "FOUNDRY_FUZZ_SEED=$(
                    echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
                  )" >> $GITHUB_ENV
            
            - name: "Build the contracts and print their size"
              run: "forge build --sizes"

            - name: "Run the tests"
              run: "forge test --nmc TypeCheck"

            - name: "Add test summary"
              run: |
                  echo "## Proposal simulator tests result" >> $GITHUB_STEP_SUMMARY
                  echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

    type-check-test:
        needs: ["lint"]
        runs-on: "ubuntu-latest"
        steps:
            - name: "Check out the repo"
              uses: "actions/checkout@v3"
              with:
                  submodules: "recursive"

            - name: "Install Foundry"
              uses: "foundry-rs/foundry-toolchain@v1"

            - name: "Show the Foundry config"
              run: "forge config"
            
            - name: "Install Node.js"
              uses: "actions/setup-node@v3"
              with:
                  node-version: "lts/*"

            - name: "Install the Node.js dependencies"
              run: "cd typescript/ && npm install && cd ../"

            - name: "Run typecheck tests"
              run: "forge test --mc TypeCheck --ffi --fork-url sepolia"

            - name: "Add test summary"
              run: |
                  echo "## Type check tests result" >> $GITHUB_STEP_SUMMARY
                  echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
